[build-system]
requires = [
    "setuptools>=64",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "linpg"
version = "3.7.0"
authors = [
    {name = "Linpg Foundation", email = "yudong9912@gmail.com"},
]
description = "A game engine based on pygame, which aims to make game development easier."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Operating System :: OS Independent",
]
dependencies = [
    "pygame-ce",
    "numpy",
    "opencv-python",
    "pillow",
    "PySimpleGUI",
    "PyYAML",
    "tcod",
]

[project.urls]
"Homepage" = "https://github.com/LinpgFoundation/linpg"
"Bug Tracker" = "https://github.com/LinpgFoundation/linpg/issues"

[tool.mypy]
python_version = "3.11"
# disallow_any_generics = true
disallow_untyped_defs = true
disallow_untyped_calls = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true

[tool.black]
line-length = 160
target-version = ['py311']

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*"]

# [options.entry_points."pyinstaller40"]
# hook-dirs = "linpg.__pyinstaller:get_hook_dirs"